### ISSUE TITLE
Add compile instrcutions

### ISSUE THREAD

**Issue by nohponex** [AlexMetsai/parallel-distributed-systems#1]
Hello,
please add compile and execution instructions.

Include the Makefile in necessary.

**Comment by AlexMetsai** [comment]
Hi nohponex, thanks for your interest!

Thowing everything in a raw folder like this was kind of sloppy, but I was in a bit of a hurry. I will include information on how to compile every file as soon as I can.

Again thanks for the help!! ^__^
